# Generated by Django 3.2.3 on 2021-05-29 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exam.address'),
        ),
        migrations.AlterField(
            model_name='school',
            name='schoolAdministrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.schooladministrator'),
        ),
        migrations.AlterField(
            model_name='school',
            name='schoolClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.schoolclass'),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.teacher'),
        ),
        migrations.AlterField(
            model_name='schooladministrator',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exam.address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exam.address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='schoolClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.schoolclass'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exam.address'),
        ),
    ]
