# Generated by Django 3.2.3 on 2021-05-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20210529_1621'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='Address',
        ),
        migrations.AlterModelTable(
            name='exam',
            table='Exam',
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='Schedule',
        ),
        migrations.AlterModelTable(
            name='school',
            table='School',
        ),
        migrations.AlterModelTable(
            name='schooladministrator',
            table='SchoolAdministrator',
        ),
        migrations.AlterModelTable(
            name='schoolclass',
            table='SchoolClass',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='Teacher',
        ),
    ]
