# Generated by Django 3.2.3 on 2021-05-30 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20210529_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='representative',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.student'),
        ),
    ]
