# Generated by Django 3.2.3 on 2021-05-30 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_schoolclass_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='branch',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I')], default='A', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='degree',
            field=models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='9', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='representative',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='exam.address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
