# Generated by Django 3.2.3 on 2021-05-30 14:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20210530_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exams',
            field=models.ManyToManyField(null=True, to='exam.Exam'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
