# Generated by Django 3.2.3 on 2021-05-30 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20210530_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='exams',
            field=models.ManyToManyField(to='exam.Exam'),
        ),
        migrations.AlterField(
            model_name='student',
            name='schoolClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.schoolclass'),
        ),
    ]
