# Generated by Django 3.2.3 on 2021-05-30 14:40

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20210530_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='exams',
            field=models.ManyToManyField(blank=True, to='exam.Exam'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
