# Generated by Django 3.2.3 on 2021-05-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20210530_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='accessKey',
            field=models.CharField(blank=True, default='abc123123', max_length=100, null=True, verbose_name='accesssKey'),
        ),
    ]
