# Generated by Django 3.2.3 on 2021-05-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20210531_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='adminAccessKey',
            field=models.CharField(blank=True, default='U2k5iBHIkYBj', max_length=100, null=True, verbose_name='adminAccesssKey'),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacherAccessKey',
            field=models.CharField(blank=True, default='Ctj3cIIWvvnV', max_length=100, null=True, verbose_name='teacherAccessKey'),
        ),
    ]
