# Generated by Django 3.2.3 on 2021-06-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20210531_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='adminAccessKey',
            field=models.CharField(blank=True, default='BxQGpVH6YZ8W', max_length=100, null=True, verbose_name='adminAccesssKey'),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacherAccessKey',
            field=models.CharField(blank=True, default='q7yQVYmZUw9W', max_length=100, null=True, verbose_name='teacherAccessKey'),
        ),
    ]
