# Generated by Django 3.2.3 on 2021-06-03 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_auto_20210601_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='exams',
        ),
        migrations.RemoveField(
            model_name='school',
            name='schoolAdministrator',
        ),
        migrations.RemoveField(
            model_name='school',
            name='schoolClass',
        ),
        migrations.RemoveField(
            model_name='school',
            name='teacher',
        ),
        migrations.AddField(
            model_name='exam',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.schedule'),
        ),
        migrations.AddField(
            model_name='schooladministrator',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.school'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.school'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.school'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='observerTeacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observer_teacher', to='exam.teacher'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='ownerTeacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_teacher', to='exam.teacher'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.schooladministrator'),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.address'),
        ),
        migrations.AlterField(
            model_name='school',
            name='adminAccessKey',
            field=models.CharField(blank=True, default='JIBBucmWilfy9knt9r', max_length=100, null=True, verbose_name='adminAccesssKey'),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacherAccessKey',
            field=models.CharField(blank=True, default='oOP8z1mcdpkDcrkUWd', max_length=100, null=True, verbose_name='teacherAccessKey'),
        ),
        migrations.AlterField(
            model_name='schooladministrator',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.address'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='representative',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='schoolClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.schoolclass'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.address'),
        ),
    ]
