# Generated by Django 3.2.3 on 2021-06-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20210603_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='adminAccessKey',
            field=models.CharField(blank=True, default='QR4qQ9z0rzXAO9K7Zr', max_length=100, null=True, verbose_name='adminAccesssKey'),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacherAccessKey',
            field=models.CharField(blank=True, default='uoJl6Ay9K1YNtLz9jA', max_length=100, null=True, verbose_name='teacherAccessKey'),
        ),
    ]
