# Generated by Django 3.2.3 on 2021-06-08 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20210603_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='adminAccessKey',
            field=models.CharField(blank=True, default='AOF84QKW2ZWd8u1r5n', max_length=100, null=True, verbose_name='adminAccesssKey'),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacherAccessKey',
            field=models.CharField(blank=True, default='5JUY8dRsPR1ti1q5nv', max_length=100, null=True, verbose_name='teacherAccessKey'),
        ),
        migrations.CreateModel(
            name='SittingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskNumber', models.PositiveIntegerField()),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.schedule')),
                ('schoolClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_class', to='exam.schoolclass')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='exam.student')),
            ],
            options={
                'db_table': 'SittingPlan',
            },
        ),
    ]
