# Generated by Django 3.2.3 on 2021-06-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20210605_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='adminAccessKey',
            field=models.CharField(blank=True, default='XTlP1YrzKTVuasQpBZ', max_length=100, null=True, verbose_name='adminAccesssKey'),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacherAccessKey',
            field=models.CharField(blank=True, default='TKJn1A3z2XuoJdYEkC', max_length=100, null=True, verbose_name='teacherAccessKey'),
        ),
    ]
