# Generated by Django 3.2.3 on 2021-06-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_auto_20210605_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='adminAccessKey',
            field=models.CharField(blank=True, default='7JfGPtVZsa68prjjcu', max_length=100, null=True, verbose_name='adminAccesssKey'),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacherAccessKey',
            field=models.CharField(blank=True, default='46GLcupc2pSlFfjCFN', max_length=100, null=True, verbose_name='teacherAccessKey'),
        ),
    ]
