# Generated by Django 3.2.3 on 2021-06-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20210608_1744'),
        ('exam', '0017_auto_20210606_1151'),
    ]

    operations = [
    ]
