# Generated by Django 3.2.3 on 2021-06-09 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_merge_0015_auto_20210608_1744_0017_auto_20210606_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.school'),
        ),
        migrations.AlterField(
            model_name='school',
            name='adminAccessKey',
            field=models.CharField(blank=True, default='dgvBmwZ0GNpY8qtguv', max_length=100, null=True, verbose_name='adminAccesssKey'),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacherAccessKey',
            field=models.CharField(blank=True, default='hVQn1fqqw1s3pAiBPr', max_length=100, null=True, verbose_name='teacherAccessKey'),
        ),
    ]
