# Generated by Django 3.2.3 on 2021-06-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_auto_20210609_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='numberOfStudents',
            field=models.IntegerField(blank=True, default=0, verbose_name='null=True'),
        ),
        migrations.AlterField(
            model_name='school',
            name='adminAccessKey',
            field=models.CharField(blank=True, default='qXYFDAgGOTzW4eiq7A', max_length=100, null=True, verbose_name='adminAccesssKey'),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacherAccessKey',
            field=models.CharField(blank=True, default='jdMuszeq68JhEZ9qhj', max_length=100, null=True, verbose_name='teacherAccessKey'),
        ),
    ]
