# Generated by Django 3.2.3 on 2021-06-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_auto_20210610_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='adminAccessKey',
            field=models.CharField(blank=True, default='WGjjj1Ssz7KyMjFyMY', max_length=100, null=True, verbose_name='adminAccesssKey'),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacherAccessKey',
            field=models.CharField(blank=True, default='tGh3JQ6N9nrVA76cwH', max_length=100, null=True, verbose_name='teacherAccessKey'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='numberOfStudents',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
