# Generated by Django 3.2.3 on 2021-06-18 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_auto_20210610_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='adminAccessKey',
            field=models.CharField(blank=True, default='f2W9SiHlH2OMfVO7Ri', max_length=100, null=True, verbose_name='adminAccesssKey'),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacherAccessKey',
            field=models.CharField(blank=True, default='hpMSnAO7s0Kxv8DCuz', max_length=100, null=True, verbose_name='teacherAccessKey'),
        ),
        migrations.AlterField(
            model_name='sittingplan',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.schedule'),
        ),
    ]
